version: "3.9"

services:
  db:
    shm_size: 1g
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=7680MB"
      - "-c"
      - "effective_cache_size=11520MB"
      - "-c"
      - "maintenance_work_mem=960MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=4915kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=8"
      - "-c"
      - "max_parallel_workers_per_gather=4"
      - "-c"
      - "max_parallel_workers=8"
      - "-c"
      - "max_parallel_maintenance_workers=4"

  manage:
    command: /bin/bash
    volumes:
      - .:/code

  web:
    stop_grace_period: 1h
    command: uwsgi --ini /app/uwsgi.ini
    ports:
      - 5000:8000
