# Generated by Django 4.0.1 on 2022-02-10 01:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_message_id', models.CharField(max_length=64, unique=True)),
                ('text_message', models.TextField()),
                ('from_phone', models.CharField(max_length=18)),
                ('from_country', models.CharField(max_length=2)),
                ('from_state', models.CharField(max_length=80)),
                ('from_city', models.CharField(max_length=80)),
                ('from_zip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms2url.message')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=20)),
                ('filesize', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms2url.message')),
            ],
        ),
    ]
